### ISSUE TITLE
Can't download videos

### ISSUE THREAD

**Issue by vanhook** [r00tmebaby/LinkedIn-Downloader#11]
One week ago I can use this python program to download video from linkedin, but today I failed to download all of the videos with error:

DevTools listening on ws://127.0.0.1:51331/devtools/browser/b1e22284-0113-4a33-af96-126f4a26db33

[*] Trying to login on LinkedIn
[*] Working on course https://www.linkedin.com/learning/building-apis-in-php-using-the-slim-micro-framework/the-request-response-flowTraceback (most recent call last):
  File "loader.py", line 390, in <module>
  File "loader.py", line 311, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".course-info__difficulty"}
  (Session info: chrome=78.0.3904.87)

[6884] Failed to execute script loader

Don't know how to fix it. Can you help me, sir ?

**Comment by r00tmebaby** [comment]
Hi Van,

Well, it still works for me. Check the video [here](https://streamable.com/00bnh)

My suggestion is to increase the timings to see if that helps. Since the message says that can not find an element that means that it does not have enough time, it could be a slow connection, dropped packets or missing element. 

Also, if you haven't logged to linked in, my advice is to do it manually. Use the starting delay option to set it for example to 500 seconds and start the program. It will then just open the browser window and wait. Use that time to log in, if you use an organisation portal that's the only way.

After successful login, just close the browser window, this is important, don't close the program but the browser window. 

Next, uncheck the login checkbox and start the program again, it should use the saved login credentials and go directly to the course as you see on the video above.

Regards

**Comment by nemises** [comment]
Hi
Mine is also still working. 
Thanks Zdravko looking good now
