### ISSUE TITLE
Quiet Frequent Error

### ISSUE THREAD

**Issue by fastmarketo** [r00tmebaby/LinkedIn-Downloader#16]
This Error si quiet frequent → 
![image](https://user-images.githubusercontent.com/6827222/69440439-db98a880-0d6e-11ea-9ac0-1e31270758cc.png)

Is there a way to fix this in future?

This doesn't happen always, but it does happen.

**Comment by r00tmebaby** [comment]
Hi,

Thanks for the report

I have worked on the project last days whenever I had free time and changed the download algorithm completely along with adding new features and fixes. Will update the repository in a few days, just want to add something else before that.

**Comment by fastmarketo** [comment]
So that means Now project files will also be downloadable? +
The downloaded video will not be re-downloaded.

**Comment by r00tmebaby** [comment]
The current algorithm which I am working on is completely different and does not use LinkedIn styles to get the video source, it does not rely on that, which I hope will bring better stability.

I am not going to announce all changes still yet, as not all of them are tested and some of them may be removed if found unreliable. 

For the project files, Yes the current version downloads the exercise files and put them in the course directory, so that feature is implemented and works well so far.

**Comment by fastmarketo** [comment]
Thanks.

**Comment by fastmarketo** [comment]
This Part is released → "For the project files, Yes the current version downloads the exercise files and put them in the course directory, so that feature is implemented and works well so far." ?

Not released yet

**Comment by r00tmebaby** [comment]
Under heavy testing now, seems to work alright. Will release it soon.

![image](https://i.gyazo.com/ea80c4d81e28352eea5ced4e67fee1c3.png)

**Comment by fastmarketo** [comment]
Great. I am waiting. I have 30 days Paid Subscription, out of which 10 days have already gone.
I look forward to and update from you. thank you so much for providing such wonderful software.
