### ISSUE TITLE
Latest update Crashing

### ISSUE THREAD

**Issue by fastmarketo** [r00tmebaby/LinkedIn-Downloader#17]
Crashing after latest Update → 
![image](https://user-images.githubusercontent.com/6827222/69895041-c7e0d980-134e-11ea-8fe1-c756d844e1bf.png)

After this, it crashes w/o downloading anything.

**Comment by r00tmebaby** [comment]
Hi, @fastmarketo,

It seems that the problem comes from chrome, for some reason can not access the hard drive. I do not have this problem and it's hard to fix something I can not reproduce.

Check whether the chrome is working and also the chrome driver itself. 

You haven't also started the new version of the program which is 0.16, from what I see you are running the older version which is 0.14 and if this version worked before, look for recent changes you made to the OS.</br>
 https://chromium.googlesource.com/chromium/src/+/f0a961b2fb8fcee156fa172b8ad00ce5e95c7a07/chrome/browser/performance_monitor/wmi_refresher.cc

**Comment by fastmarketo** [comment]
I am on a new machine as I am traveling. Are we supposed to install some Python etc on Windows desktop?
What are the checklist for the successful running of this script?

**Comment by r00tmebaby** [comment]
The latest version is executable only and nothing is needed to run it under Windows.

For the old version 0.14, if you want to run the script only through the console, you need to install fresh Python 3.7+ and then the following  libraries:

pip install selenium 
pip install colorama 
pip install tqdm 
pip install pysimplegui

You run it through the console by navigating to the source path and typing ->  python gui.py or just gui.py

Keep in mind that the program does not have a buffer which means if the connection cut out (since you are travelling it may happen) it's very likely the program to stop immediately.

**Comment by fastmarketo** [comment]
0.16 version that I downloaded doesn't have GUI and LOADER.
![image](https://user-images.githubusercontent.com/6827222/69900335-cc7db000-1397-11ea-998c-fb49b4e82bbe.png)

![linkedin_downloader](https://user-images.githubusercontent.com/6827222/69900485-f6d06d00-1399-11ea-9e81-cf8be0510520.gif)

**Comment by r00tmebaby** [comment]
Yes, v0.16 is executable only and everything is built in it. Python code is not provided.

If you read carefully in my previous post I mentioned version 0.14, not 0.16

**Comment by fastmarketo** [comment]
Please forgive me for re-opening this thread. Everything is executable that's ok, but if we use that version than where should we put Username/Password, download Links and path where the files are to be saved.

**Comment by fastmarketo** [comment]
Sir, Can you please reply on this post. Thanks.
