### ISSUE TITLE
No errors, but also not downloading

### ISSUE THREAD

**Issue by fastmarketo** [r00tmebaby/LinkedIn-Downloader#21]
It does nothing Just this and then closes → 
![image](https://user-images.githubusercontent.com/6827222/70400275-13cb0700-1a50-11ea-95f9-11f23fab671a.png)

![image](https://user-images.githubusercontent.com/6827222/70400269-0b72cc00-1a50-11ea-990a-2a248a4001d9.png)

![image](https://user-images.githubusercontent.com/6827222/70400285-33fac600-1a50-11ea-93fc-b1b757c6fe18.png)

Not a single video is downloaded. No errors too.

**Comment by fastmarketo** [comment]
If I use version 0.16 then this errors come:
![image](https://user-images.githubusercontent.com/6827222/70434114-553bd080-1aa9-11ea-8ff2-f63d9482e437.png)

**Comment by Mvk101** [comment]
> If I use version 0.16 then this errors come:
> ![image](https://user-images.githubusercontent.com/6827222/70434114-553bd080-1aa9-11ea-8ff2-f63d9482e437.png)

I have had the similar issue but then I changed the browser to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" and skipped auto login (manually open linkedin and login) and it's been working like a charm since then. I am using Windows 10 on a virtual box 6.0. 
![image](https://user-images.githubusercontent.com/29660877/70488846-cdf15b80-1aae-11ea-9ac8-0d3a6e84a043.png)

**Comment by fastmarketo** [comment]
I did as you suggested, but got the same error → 
![image](https://user-images.githubusercontent.com/6827222/70489578-32013780-1b22-11ea-9f54-acb45e475479.png)


And nothing worked.

**Comment by Mvk101** [comment]
Which OS you're using and is it a 32 or 64 bit? Honestly, I would just randomly try few other browsers from the drop-down and see if it works.

**Comment by fastmarketo** [comment]
Licensed Window 7 →  64 Bit.

**Comment by Mvk101** [comment]
try Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0 
or 
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; yie11; rv:11.0) like Gecko

**Comment by fastmarketo** [comment]
Sir,

I tried the same issue. Even the previous versions also do not work any more.

**Comment by r00tmebaby** [comment]
Hi there,

I missed the last conversations.

For the browser agents, you can use those from the select form (Google Adbot is a good choice as no one will block such) or choose another from <a target="a_blank" href='https://developers.whatismybrowser.com/useragents/explore/'>here </a>

You use version 0.16, could you try 0.16.1 executable and report if you have the same issue. In the meantime, I will try to reproduce the error.

PS. Don't use version 0.14 anymore, it's not reliable, I have fixed many minor issues.

**Comment by fastmarketo** [comment]
Let me try I will report it soon. Thanks.

**Comment by fastmarketo** [comment]
Same error:

![image](https://user-images.githubusercontent.com/6827222/70523663-8bd92000-1b69-11ea-9820-4ec334779fee.png)


![image](https://user-images.githubusercontent.com/6827222/70523704-9e535980-1b69-11ea-96db-ddfbd0dc6cf3.png)

**Comment by r00tmebaby** [comment]
Use the manual login

**Comment by fastmarketo** [comment]
Sir, still the same.

**Comment by r00tmebaby** [comment]
Which courses are you working on? Send me the links, please.

**Comment by fastmarketo** [comment]
Hey There,

https://www.linkedin.com/learning/conquering-writer-s-block
https://www.linkedin.com/learning/succeeding-as-an-in-house-creative

Thanks.

**Comment by r00tmebaby** [comment]
I was not able to reproduce the error you got. It works ok in my case. Can you give me a screenshot of the window?

**Comment by fastmarketo** [comment]
Hi there,

![image](https://user-images.githubusercontent.com/6827222/70554663-8e586b80-1ba3-11ea-96cf-6ebbfa624865.png)

**Comment by r00tmebaby** [comment]
I meant the browser window when you start the program, dear... not the system information.  

The question is does this Chrome window opens and if yes, what do you see? Does it do any activity?

**Comment by fastmarketo** [comment]
I have created a GIF and send it on your email because some private information was there that can't be posted on the forum.

**Comment by r00tmebaby** [comment]
Ok

**Comment by fastmarketo** [comment]
I hope you have received it in the email.

**Comment by r00tmebaby** [comment]
Yes, I got it.

**Comment by r00tmebaby** [comment]
The program can not find the video content. The course videos for some reason are hidden on the left top corner in your browser (too small window I guess) as in mobile version.

I have a suggestion. 

Could you try to add some delay time and once the browser window opens, clear its cache and then restart the program. After the restart maximizes the browser window and sees what will happen.

Let me know about the results.

**Comment by fastmarketo** [comment]
Sure, Thanks for all the support. I will update you soon.

**Comment by fastmarketo** [comment]
Hello sir,

I cleared the cache since the beginning of the time.
I deleted all the files of your software and then redownloaded them.
Increased the size of the window as suggested by you.

But the same error on both of my Laptop and Desktop **→** 
![image](https://user-images.githubusercontent.com/6827222/70590757-ad81e800-1bf9-11ea-9084-bc9dd0502733.png)

**Comment by fastmarketo** [comment]
Sir,

You are not charging a single dime, but helping so much. thank you so much for that. 

If possible please give us a remedy. Again, sir, You are not liable but if you can find a solution then I will be thankful and grateful to you as that will solve my downloading issues.

**Comment by r00tmebaby** [comment]
It's very interesting. I do not see the videos on the screenshot in the way the program is looking for them.

When you log in and having a full window size you should see something like this -> <img src='https://i.imgur.com/LjYtVQz.png'> 

As you can see on the right top corner you have your login information/picture if you uploaded one then below there should be some tabs, one of which is called "content", that place is crucial for the program because the videos are not visible until this tab is clicked. You got a message that the program can not find this tab element to click on it, which means it's somewhere hidden or is missing.

So my question is, did you change anything to the LinkedIn UI look, like changing the template or something else? If you did, try to bring it back to the original state. 

In general, your profile looks completely different than mine and I can not debug the program without having this look, unfortunately.

**Comment by fastmarketo** [comment]
Let me do everything I can i will get back to you. May be they have changed layout and you are seeing old layout.

**Comment by fastmarketo** [comment]
I have sent them mail. I think they have changed the layout. You cant see because you have cache.

**Comment by r00tmebaby** [comment]
> I have sent them mail. I think they have changed the layout. You cant see because you have cache.

I cleared my browser cache and logged with newly created account and the layout is still the same as before. There is definitely something in your account. <img src='https://i.gyazo.com/60cbb03648c98aa8827ac050cdb578b4.png'>

Is it the same with any course that you are trying to download or just that one?

**Comment by fastmarketo** [comment]
I think this is with every video.

Additionally, 

22 NOV - Layout OK when I was using LinkedIn on desktop.

I traveled to my parent's home and there was using a Sony laptop where chrome was synchronized. The layout changed, but
on Dec 9 when I came back since then the same new layout is also there on my desktop(where everything was ok before).

**I think the new layout is a global change.** (Not sure)

**Comment by r00tmebaby** [comment]
It's not a global change for sure (if there is a change at all, I do not really believe in that), because other people use the program without a problem and see what I see as a layout. 

I do not see on your screenshot where is the account picture, should be on the right top corner.
Are you sure that you have logged at all and do you have a premium? You should see your account name on the right top in anyways. As in the picture below. You have to also see a lot more videos not just what you got as content for this particular course. 

Maybe the program does not read the saved credentials and if that is so, my suggestion is to uninstall and install (don't overwrite the existing one, uninstall the previous installation completely) the Chrome browser again. In any case, I would do it at least to remove that from the possibilities list.

<img src='https://i.gyazo.com/8c89ccd46adf9d3bd98a007145e37269.png'>

**Comment by fastmarketo** [comment]
> It's not a global change for sure (if there is a change at all, I do not really believe in that), because other people use the program without a problem and see what I see as a layout.

Profile Picture is there → 
![image](https://user-images.githubusercontent.com/6827222/70681335-11231880-1cc1-11ea-96c5-00ccdffc2529.png)


> Are you sure that you have logged at all and do you have a premium?

Yes, My Premium is still valid till December 18.

> Maybe the program does not read the saved credentials and if that is so, my suggestion is to uninstall and install (don't overwrite the existing one, uninstall the previous installation completely) the Chrome browser again.

Should I install and uninstall chrome browser once again?

**Comment by fastmarketo** [comment]
Sir,

The video list is still available but in a different format.
![list_butdiff](https://user-images.githubusercontent.com/6827222/70682295-6b71a880-1cc4-11ea-90d9-382c9c561ffb.gif)

**Comment by fastmarketo** [comment]
I think this could not be solved as their support is giving copy paste idiotic replies w/o trying to understand what the question is.

**Comment by r00tmebaby** [comment]
Sorry, I can not help now without having the same UI.

**Comment by armia142** [comment]
![2019-12-21 20_59_48-C__Users_Armia_Downloads_LinkedIn-Downloader-master_LinkedIn-Downloader-master_W](https://user-images.githubusercontent.com/40745071/71312580-3fc58f80-2435-11ea-983e-a1cb1558cbb6.png)
![2019-12-21 21_00_56-395 Properties panel_ Tips for the new user](https://user-images.githubusercontent.com/40745071/71312581-405e2600-2435-11ea-9359-df1f06e182c4.png)

Please I got the same thing just in consideration that it was working fine for 2 weeks

**Comment by fastmarketo** [comment]
Maybe this is Linkedin's method to combat the automation download of the Videos. I suffered from the same a/c issues.
