### ISSUE TITLE
tutorials how to use it

### ISSUE THREAD

**Issue by maxiaoan** [r00tmebaby/LinkedIn-Downloader#3]
can you add tutorials  on ** README.MD**  to tell us how to use it
Can it download lynda videos via linkedIN account?

**Comment by r00tmebaby** [comment]
Hello, maxiaoan

Yes, I will put some more information on how to use it.

To be honest, I was planning to create a video tutorial and explain how it works, but because was not sure that there will be any interest left the idea.

Can it download lynda videos via linkedIN account? - Yes, this is what it actually does. It can log in with your LinkedIn Learning account and download the videos that you put into the list.

Regards

**Comment by r00tmebaby** [comment]
https://www.youtube.com/watch?v=n-qCC6SiKgc&feature=youtu.be
