### ISSUE TITLE
Pausing downloads or resuming downloads after network interruption 

### ISSUE THREAD

**Issue by Frasusan** [r00tmebaby/LinkedIn-Downloader#30]
How to you pause downloads or resume downloads after network failure?

**Comment by r00tmebaby** [comment]
There is no such functionality implemented yet. 

If the connection is lost the program will stop working and since there is no buffer or tracking where it was before that issue appear, continuing from there is not possible.

Such an update is not planned. You need a stable internet connection to be able to use this software.
