### ISSUE TITLE
Version 0.16.2 seems to have a trojan which 0.16.1 didn't have

### ISSUE THREAD

**Issue by delta0815** [r00tmebaby/LinkedIn-Downloader#35]
I've unpacked the windows executable of 0.16.2 and Microsoft defender blocks access because of this: "Trojan:Win32/Wacatac.C!ml". I know you include the sourcecode as a proof so it might be a false alert I was just wondering why this didn't happen with 0.16.1

Cheers,

delta0815

**Comment by r00tmebaby** [comment]
It seems that not only my program has a false-positive report for exactly the same thing. Since the program is not commercial I see no point to bother and report to Microsoft that the program is clean etc. 

https://superuser.com/questions/1416678/my-own-backup-program-was-detected-as-win32-bearfoos-aml-virus

**Comment by fastmarketo** [comment]
Linkedin is a Microsft co. Probably they are monitoring us and their software doesn't this warning knowingly.
