### ISSUE TITLE
List of downloaded video files

### ISSUE THREAD

**Issue by Yoss5** [r00tmebaby/LinkedIn-Downloader#4]
Hi Zdravko,

Nice work, as far as I know only working downloader for LinkedIn at this time.
Only issue I found:
it repeats the first video file, usually some introduction or welcome
and misses the last one, usually conclusions or next steps.

I tried it with several courses. First thought, maybe the autoplay-on causes this but  turning it off did not solve it.
Anyway, apart from that it really works well.
Thanks.
BR,
A

**Comment by r00tmebaby** [comment]
Hi, 
Thanks for the feedback and report. This is very important to me so I can fix the issues accordingly. 

Yes, I knew that the first video is downloading twice before the release but didn't catch that the last video is not downloaded. I have an idea where the problem is coming from.

I haven't had the time to work on the project for a while but will continue soon.
