### ISSUE TITLE
Videos not downloading

### ISSUE THREAD

**Issue by thedarkkid** [r00tmebaby/LinkedIn-Downloader#44]
When I try to download any course it gives this error:

`[6516:12904:0313/180821.481:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -107
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedDL.py", line 369, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 530, in find_element_by_tag_name
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"video"}
  (Session info: chrome=80.0.3987.132)`

**Comment by r00tmebaby** [comment]
Hi, which version are you using?

**Comment by thedarkkid** [comment]
Hi, version 0.16.5 v2

**Comment by r00tmebaby** [comment]
Try to increase download times. What is the course name?

**Comment by thedarkkid** [comment]
https://www.linkedin.com/learning/programming-foundations-algorithms
that is the course, it has stopped showing that error, now it shows 
`loader: error: unrecognized arguments: https://www.lynda.com/Google-Analytics-tutorials/SEO-Foundations/604242-2.html`
even though I am trying to download a different course

**Comment by r00tmebaby** [comment]
https://www.youtube.com/watch?v=FKPZeyM7098&feature=youtu.be

Hope that this video will help you download what you want. 

The versions are different from each other but the courses databases have always been in Lynda.com. So that being said you need to find the original course name on Lynda.com and then use the Lynda downloader. Lynda downloader at this point does not need login because I have added my own cookie that still works. What version  0.16.5 v2 does is actually doing what is shown on the video automatically to get the course name from LinkedIn and relate it to Lynda. Of course, manual list adding is the best you can do.

I also highly recommend you to use this list https://github.com/r00tmebaby/LinkedIn-Downloader/blob/master/Lynda%20Courses%20Dump/LyndaCourseList%2008.03.2020.txt which is the complete course list available at the moment. 

You can simply select copy and paste the courses that you need to coursesList.txt and use this downloader https://github.com/r00tmebaby/LinkedInDownloader/tree/master/LyndaDL%20Executable's

Of course, you can use version 1.16.5 which is faster but needs a LinkedIn learning account and login which creates a hash that Lynda uses to unlock the videos.  

That is why I have put all the things that I have made in regards to Lynda/Linked in learning in one place so you can eventualy find whatever suits you best.

**Comment by thedarkkid** [comment]
Okay, thanks a lot, I’d check it out.

**Comment by thedarkkid** [comment]
It's working now, thanks

**Comment by x-civix-x** [comment]
same issue (unrecognized arguments) but for linkedin videos, not avaiable on Lynda. How can i do ?

**Comment by imdurgeshranjan** [comment]
https://www.lynda.com/Docker-tutorials/Docker-Developers/2211315-2.html 
this course does not download even though I am trying to download a different course

**Comment by winstongarasu** [comment]
Hi, I used your code and tried to download the below course, but only the first video in each folder gets downloaded. 
https://www.lynda.com/Revit-Structure-tutorials/Revit-2020-Essential-Training-Structure-Imperial/5019798-2.html
Also, I want to download the same tutorial in metric format(Revit-2020-Essential-Training-Structure-Metric), but the link to download is not available in your database. Can you look into this?  This will be a great help.
