### ISSUE TITLE
doesn't download any video, just directories

### ISSUE THREAD

**Issue by percysl** [r00tmebaby/LinkedIn-Downloader#59]
the script lists the directories and stops at the zip file, but there's no any video

**Comment by r00tmebaby** [comment]
Hi,

What you are using, Linked or LyndaDL?

When you report an issue, specify which application you're using, what version  (if any), console logs (if any) and at least which course you are trying to download so I can try to reproduce the error or if it is false positive to provide you with steps how to do it.

For now, what you say is "I have a problem" ... and we all do actually 

Regards

**Comment by Maloto7** [comment]
I have the same problem, only a few videos download with the 0.16.5 v2 and with the 0.16.4 does not download noting.

https://github.com/Maloto7/issues/tree/master/eLearning

**Comment by r00tmebaby** [comment]
Hi there,

Try this  method and tool https://github.com/r00tmebaby/LinkedIn-Downloader/tree/master/LyndaDL%20Executable's  

I am not planning to update Linkedin DL
Cheers

**Comment by percysl** [comment]
> Hi there,
> 
> Try this method and tool https://github.com/r00tmebaby/LinkedIn-Downloader/tree/master/LyndaDL%20Executable's
> 
> I am not planning to update Linkedin DL
> Cheers

Hi

Thank you for your recommendations, I am new here. Linkedin DL (0.16.5 v2) is not working. I don't have subscription in Lynda. May I ask you what can I do to have the script working?

Thank you.

**Comment by Maloto7** [comment]
I follow the step of the video for Lynda an only half of the videos download only the videos until folder 6 the other does not have videos. (folder 7, 8, etc are empty)
https://github.com/Maloto7/issues/tree/master/Lynda

**Comment by arestelli** [comment]
Hi Zdravko,
thanks for your great work!
I'm using the executable LyndaDL.exe with the provided cookie, it worked fine for more than a month but starting from yesterday it dowloads only the free videos and skips completely the locked ones. I don't think it's the cookie cause it says "Logged in successfully".
Can you please verify?

Thanks.
![LyndaDL](https://user-images.githubusercontent.com/18467404/80667125-8d669e80-8a9e-11ea-9cc3-0e97a7435309.gif)

**Comment by ahsenabro** [comment]
I have the same problem as "arestelli".
Using LyndaDL.exe.
Worked fine for a month for the past couple of days, only downloads free videos and not the locked videos.
Please fix this problem. 
Will donate.

**Comment by ahsenabro** [comment]
It skips over the locked videos but creates empty directories with no videos. Only downloads free videos, not locked ones.

![LyndaDL error](https://user-images.githubusercontent.com/57742183/80769956-447b1c80-8b68-11ea-82a4-d4ee51697fd4.JPG)

**Comment by sinnans** [comment]
Looks like Lynda / LinkedIn must have done some arrangement to restrict the downloading. However I can still able to download manually!

**Comment by ahsenabro** [comment]
> Looks like Lynda / LinkedIn must have done some arrangement to restrict the downloading. However I can still able to download manually!

What do you mean by downloading manually? Using Lynda 'App' thing or are you able to mass download using a list of URLs? If latter, how are you doing it? Please help others.

**Comment by sinnans** [comment]
> > Looks like Lynda / LinkedIn must have done some arrangement to restrict the downloading. However I can still able to download manually!
> 
> What do you mean by downloading manually? Using Lynda 'App' thing or are you able to mass download using a list of URLs? If latter, how are you doing it? Please help others.

By manually downloading I meant that you can still download each video if you have active account. and search the video link in the source code and that's it. It is just they have disabled Right Clicks on the website but in the code there is a link behind the video.

But using script by r00tmebaby makes work much efficient and also organized too, plus it also saves titles files.

**Comment by knighthawk65** [comment]
And how do you do this manually. Because I am having same trouble that it downloads 4 videos from course and the other have empty directories. I have an active linkedin account I use. And where I search the video link in the source code and that's it. It is just they have disabled Right Clicks on the website but in the code there is a link behind the video.

**Comment by r00tmebaby** [comment]
Hi all,

Sorry for being inactive for a while.

Honestly, I have no interest left in this project, to keep it up to date working and so on. 

The nature of this kind of things is dynamic one of the main reasons why most if not all other projects providing the same thing do not work is because you have to adjust it to the changes Lynda and Linked do make. That is not hard to do, but it is really impossible if you already learned whatever you wanted to as in my case. 

From a developer perspective, there is nothing left in this project that can keep my interest. The code is shared so anyone interested to use part of it for his project or decide to improve this one is more than welcome. 

In terms of the current functionality, I have provided you with my own cookie.txt file that contained my login credentials for Lynda.com. That is why the program worked right out of the box for a while until obviously, Lynda has caught that there is unusually high traffic under this account and probably blocked or downgraded it to free account. I haven't checked that just guessing why you can not download the full courses but only the free content. Please disregard the message "Logged in successfully" it is not evidenced that it is actually logged with a premium account, as you may have logged with a free account and still use the free content.

So the main thing that you have to do to keep the program working as expected is to have Lynda account (not LinkedIn) so to be able to use the Lynda version of the software which is by the way better. After having an account you have to extract the login header and paste it in the cookie.txt file.

I hope that you all understand my point.
Regards,
