### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by miguelitoxrox** [r00tmebaby/LinkedIn-Downloader#6]
Hey thanks for update! now another little problem... when find a test app stop, dont donload anymore and say:

Traceback (most recent call last):
  File "loader.py", line 368, in <module>
  File "loader.py", line 331, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 530, in find_element_by_tag_name
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"video"}
  (Session info: chrome=75.0.3770.142)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.10240 x86_64)

[12256] Failed to execute script loader

**Comment by r00tmebaby** [comment]
Hi,

Considering the message for some reason, the program can not find the video which contains download link and obviously can not download it. 

I will try to reproduce the error. I would be thankful if you make a screenshot of the browser window so we can see why the software can not get the video tag. 

I am just guessing that it could be some unexpected popup window, 404 error or 429 (too many requests) etc.

**Comment by jw1060737** [comment]
Same error for me

**Comment by miguelitoxrox** [comment]
Palease fix this

**Comment by r00tmebaby** [comment]
Hello Everybody,

Sorry for the late reply, as most of us I was on a summer holiday and didn't not have the time and desire to work on the project during that time.

I have reproduced the error and came up with the conclusion that LinkedIn most probably blocked the User-Agent signature because after I have changed it to IE without touching anything else the software worked properly. I suspect that some of you if not all do not change the browser signature and this obviously leads to high traffic to this particular agent which is suspicious. In the current updated version, I have added an option so you can select from the existing or add your own browser agent signature so everyone can be unique. Should you wonder how/or where to find the user agent., please check and select some from the list: [https://udger.com/resources/ua-list ](url)

It is recommended to change the User-Agent and use VPN/Proxy regularly to avoid your IP get blocked. You may get "Too many requests" error as Linked has a limited amount of requests per account (per account! not IP) a day. If you get such an error, do not worry it will be restored automatically in the next 12-24 hours.

From what I have examined during the software testing, you can download around 8-10GB a day before getting that error if it ever occurs. In future updates as mentioned, I will add an option to delay the download time to reduce the chance of happening.

All the best,
r00tme
