### ISSUE TITLE
Skipping most files though it was perfectly working 7 days back when I downloaded bunch of courses.

### ISSUE THREAD

**Issue by sinnans** [r00tmebaby/LinkedIn-Downloader#60]
I was using the LyndaDL executeable with listed course links of lynda.com urls (not LinkedIn) it was working fine however now it is skipping most of the files (those which are locked). in short now the LyndaDL is working to download only those lecture videos who were already public and free to view.

Folders for each chapters are still being created. If none of the lecture is free than that folders remain empty as no video downloads.

![Capture](https://user-images.githubusercontent.com/61533577/80774380-51067180-8b76-11ea-9cc4-d90d261af5ae.PNG)

**Comment by ahmed21997** [comment]
the same issue it only downloads the free videos of the course

**Comment by r00tmebaby** [comment]
Yes, obviously Lynda recognised the high activity related to the cookie.txt file that I have provided with the release. I did not expect to work even that long to be honest since everyone is using it.

Should you want to use the program as before, you will need to have your own account and extract the cookie into the cookie.txt.
